# Generated by Django 2.2.7 on 2020-03-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cart_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
